In [1]:
# 矩阵操作

In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [4]:
# 创建矩阵

In [5]:
# 对角矩阵
help(tf.diag)

Help on function diag in module tensorflow.python.ops.gen_array_ops:

diag(diagonal, name=None)
    Returns a diagonal tensor with a given diagonal values.
    
    Given a `diagonal`, this operation returns a tensor with the `diagonal` and
    everything else padded with zeros. The diagonal is computed as follows:
    
    Assume `diagonal` has dimensions [D1,..., Dk], then the output is a tensor of
    rank 2k with dimensions [D1,..., Dk, D1,..., Dk] where:
    
    `output[i1,..., ik, i1,..., ik] = diagonal[i1, ..., ik]` and 0 everywhere else.
    
    For example:
    
    ```
    # 'diagonal' is [1, 2, 3, 4]
    tf.diag(diagonal) ==> [[1, 0, 0, 0]
                           [0, 2, 0, 0]
                           [0, 0, 3, 0]
                           [0, 0, 0, 4]]
    ```
    
    Args:
      diagonal: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `int32`, `int64`, `complex64`, `complex128`.
        Rank k tensor where k is at most 1.


In [6]:
identity_matrix = tf.diag([1., 1.,1.])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
A = tf.zeros(shape=[2, 3], dtype=tf.float32)
print(sess.run(A))

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
B = tf.ones(shape=[3, 3], dtype=tf.float32)
print(sess.run(B))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
C = tf.fill([3, 3], 2)
print(sess.run(C))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [12]:
D = tf.constant([[2, 3, 4], [4, 5, 6]])
print(sess.run(D))

[[2 3 4]
 [4 5 6]]


In [14]:
E = tf.random_uniform([3, 3], minval=0, maxval=2, dtype=tf.float32, seed=1234)
print(sess.run(E))

[[1.696614   0.64714265 0.6134002 ]
 [0.13939953 1.827713   0.34095812]
 [0.5667424  0.7125411  1.0831125 ]]


In [15]:
F = tf.random_normal([3, 3], mean=0., stddev=1., dtype=tf.float32, seed=1234)
print(sess.run(F))

[[ 0.51340485 -0.255814    0.6519913 ]
 [ 1.3923638   0.37256798  0.20336303]
 [ 1.2470183  -0.98333126  0.5043986 ]]


In [16]:
G = tf.truncated_normal([3, 3], mean=0., stddev=1., dtype=tf.float32, seed=1234)
print(sess.run(G))

[[ 0.51340485 -0.255814    0.6519913 ]
 [ 1.3923638   0.1662533  -0.9161797 ]
 [ 0.10719004  0.32142618 -0.4303575 ]]


In [17]:
# 还可以直接从numpy数组或者列表转为张量矩阵
import numpy as np

H = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
H_tsr = tf.convert_to_tensor(H)
print(H)
print('-----------------------')
print(sess.run(H_tsr))

[[1 2 3]
 [4 5 6]
 [9 8 7]]
-----------------------
[[1 2 3]
 [4 5 6]
 [9 8 7]]


In [21]:
I = [[2, 3, 4], [5, 4, 3], [5, 3, 1]]
print(I)

[[2, 3, 4], [5, 4, 3], [5, 3, 1]]


In [22]:
I_tsr = tf.convert_to_tensor(I)
print(sess.run(I_tsr))

[[2 3 4]
 [5 4 3]
 [5 3 1]]


In [3]:
# 矩阵的加，减，乘运算
A = tf.truncated_normal([2, 3])
B = tf.fill([2, 3], 5.)
print(sess.run(A))
print('=================')
print(sess.run(B))

[[ 0.4106862   0.15785116 -0.34511495]
 [ 0.6949497  -0.8491212  -1.844407  ]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [4]:
add_ = A + B
print(sess.run(add_))

[[5.7266054 4.67933   5.744187 ]
 [6.290207  5.538105  4.1336303]]


In [5]:
sub_ = B - B
print(sess.run(sub_))

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
identity_matrix = tf.diag([1., 1., 1.])
mul_ = tf.matmul(B, identity_matrix)
print(sess.run(mul_))

[[5. 5. 5.]
 [5. 5. 5.]]


In [7]:
help(tf.matmul)

Help on function matmul in module tensorflow.python.ops.math_ops:

matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
    Multiplies matrix `a` by matrix `b`, producing `a` * `b`.
    
    The inputs must, following any transpositions, be tensors of rank >= 2
    where the inner 2 dimensions specify valid matrix multiplication arguments,
    and any further outer dimensions match.
    
    Both matrices must be of the same type. The supported types are:
    `float16`, `float32`, `float64`, `int32`, `complex64`, `complex128`.
    
    Either matrix can be transposed or adjointed (conjugated and transposed) on
    the fly by setting one of the corresponding flag to `True`. These are `False`
    by default.
    
    If one or both of the matrices contain a lot of zeros, a more efficient
    multiplication algorithm can be used by setting the corresponding
    `a_is_sparse` or `b_is_sparse` flag to `True`. T

In [8]:
print(B.shape)
print(identity_matrix.shape)

(2, 3)
(3, 3)


In [9]:
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 矩阵的转置
C = tf.random_normal([3, 2], seed=1234)
print(sess.run(C))
print('-------------------------------')
C_t = tf.transpose(C)
print(sess.run(C_t))

[[ 0.51340485 -0.255814  ]
 [ 0.6519913   1.3923638 ]
 [ 0.37256798  0.20336303]]
-------------------------------
[[0.96462417 0.24251089 1.6574976 ]
 [0.34291974 1.0578597  0.8210897 ]]


In [14]:
D = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
print(sess.run(D))
print('---------------------------------')
D_t = tf.transpose(D)
print(sess.run(D_t))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
---------------------------------
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [15]:
# 计算行列式
res = tf.matrix_determinant(D)
print(sess.run(res))

0.0


In [18]:
# 矩阵的逆
A = tf.random_uniform([3, 3], minval=0., maxval=3)
A_inv = tf.matrix_inverse(A)
print(sess.run(A_inv))

[[-0.03059805 -1.4001659   0.5701229 ]
 [-0.30465177  0.59667075  0.19589916]
 [ 0.5366438   1.1479018  -0.62800497]]


In [19]:
res = tf.matmul(A, A_inv)
print(sess.run(res))

[[1.0000000e+00 4.7683716e-07 0.0000000e+00]
 [0.0000000e+00 1.0000010e+00 2.3841858e-07]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]


In [20]:
sess.close()