In [2]:
# 更多的运算操作
import tensorflow as tf

sess = tf.Session()

In [3]:
# 除法运算div返回的是和输入一样种类的值，比如
print(sess.run(tf.div(3, 4)))  # 将返回整数

0


In [4]:
print(sess.run(tf.div(3., 4)))  # 将返回浮点

0.75


In [5]:
# 而truediv则返回浮点，不管输入的种类
print(sess.run(tf.truediv(3, 4)))

0.75


In [6]:
print(sess.run(tf.truediv(4, 2)))

2.0


In [8]:
# 还有一种地板除法
print(sess.run(tf.floordiv(3., 4)))

0.0


In [9]:
# 取余数的函数mod
print(sess.run(tf.mod(22., 5.)))

2.0


In [10]:
# tangent函数
print(sess.run(tf.tan(3.1416 / 4)))

1.0000036


In [17]:
# 定义自己的运算
def custom_polynomial(value):
    return tf.subtract(3 * tf.square(value), value) + 10

In [19]:
print(sess.run(custom_polynomial(11)))

362


In [20]:
# 激活函数的实现，我们可以直接使用tf.nn库里面的激活函数，也可以自己定义
print(sess.run(tf.nn.relu([-3., 3., 10.])))

[ 0.  3. 10.]


In [21]:
A = tf.constant([[-2, 3, -1], [3, -2, 10]], dtype=tf.float32)
print(sess.run(A))
print('------------------------------')
print(sess.run(tf.nn.relu(A)))

[[-2.  3. -1.]
 [ 3. -2. 10.]]
------------------------------
[[ 0.  3.  0.]
 [ 3.  0. 10.]]


In [23]:
# relu6函数，min(max(0, x), 6)
print(sess.run(tf.nn.relu6([-3., 3., 10.])))

[0. 3. 6.]


In [24]:
# sigmoid函数的表达式为1/(1+exp(-x))，缺点是饱和性和输出不为0均值而导致的更新缓慢
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[0.26894143 0.5        0.7310586 ]


In [25]:
# tanh函数的表达式为(exp(x) - exp(-x)) / (exp(x) + exp(-x))，它的输出是0均值的
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.7615942  0.         0.7615942]


In [26]:
sess.close()