In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [4]:
# tf.where()
a = tf.constant(value=[[1, 0, 0], [0, 1, 1]])
sess.run(tf.equal(a, 1))

array([[ True, False, False],
       [False,  True,  True]])

In [6]:
b = tf.where(a)
sess.run(b)

array([[0, 0],
       [1, 1],
       [1, 2]])

In [7]:
a1 = tf.constant(value=[[3, 2, 3], [4, 5, 6]])
c = tf.where(tf.equal(a, 1), a1, 1-a1)
sess.run(c)

array([[ 3, -1, -2],
       [-3,  5,  6]], dtype=int32)

In [10]:
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
x = tf.constant(value=[29.05088806,  27.61298943,  31.19073486,  29.35532951,
30.97266006,  26.67541885,  38.08450317,  20.74983215,
34.94445419,  34.45999146,  29.06485367,  36.01657104,
27.88236427,  20.56035233,  30.20379066,  29.51215172,
33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(tf.greater(x, 30))
print(sess.run(indices))
print('------------------------------')
out = tf.gather(x, indices)
print(sess.run(out))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
------------------------------
[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [13]:
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
diag = tf.range(start=1, limit=7)
print(sess.run(diag))
print('-------------------------')
out = tf.diag(diag)
print(sess.run(out))

[1 2 3 4 5 6]
-------------------------
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [15]:
diag = tf.range(8)
print(sess.run(diag))
print('--------------------------')
out = tf.diag(diag)
print(sess.run(out))

[0 1 2 3 4 5 6 7]
--------------------------
[[0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 7]]


In [16]:
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
x = tf.random_normal(shape=[10, 10], name='x')
out = tf.matrix_determinant(x)
print(sess.run(out))

-832.71655


In [17]:
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
# 注意，tf.unique返回的是一个元组，分别是不重复的结果和索引
x = tf.constant(value=[5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
out, out_index = tf.unique(x)
print(sess.run(out))
print('----------------------------')
print(sess.run(out_index))

[ 5  2  3 10  6  4  1  0  9]
----------------------------
[0 1 2 0 3 4 1 2 5 1 6 6 7 8]


In [36]:
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
x = tf.random_normal(shape=[300], name='x')
y = tf.random_normal(shape=[300], name='y')
z = x - y
fn1 = lambda: tf.reduce_mean(tf.square(z))
fn2 = lambda: tf.reduce_sum(tf.abs(z))
out = tf.cond(tf.less(tf.reduce_mean(z), 0), fn1, fn2)
print(sess.run(out))

1.8653015
